name: Wasm

on:
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - ".github/workflows/wasm.yaml"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  binary: leiden
  use_git_lfs: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: ${{ env.use_git_lfs }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: Build
        run: |
          cargo build --profile wasm-release --target wasm32-unknown-unknown
          wasm-bindgen --no-typescript --out-name ${{env.binary}} --out-dir wasm --target web target/wasm32-unknown-unknown/wasm-release/${{ env.binary }}.wasm
      - name: Binaryen wasm-opt
        run: |
          sudo apt-get update
          sudo apt-get install binaryen
          wasm-opt -Oz wasm/${{env.binary}}_bg.wasm -o wasm/${{env.binary}}_bg.wasm
      - name: Copy assets
        run: cp -r assets wasm/
      - name: Upload binaries to artifacts
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./wasm
          retention-days: 1
          name: github-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
